[Fixme] Revert "Define sockaddr_storage in bionic"
This reverts commit d27506716af69ede1334cbd5163186c10ab56a0f.

/mnt/exthdd/sources/pdcaf/out/soong/.intermediates/bionic/libc/libc/android_vendor.33_arm_armv8-2a_kryo385_shared/
gen/include/sys/socket.h:73:8: error: redefinition of '__kernel_sockaddr_storage'
struct sockaddr_storage {
       ^
/mnt/exthdd/sources/pdcaf/out/soong/.intermediates/vendor/pixeldust/build/soong/generated_kernel_includes/gen/usr/
include/linux/socket.h:24:26: note: expanded from macro 'sockaddr_storage'
                         ^
/mnt/exthdd/sources/pdcaf/out/soong/.intermediates/vendor/pixeldust/build/soong/generated_kernel_includes/gen/usr/
include/linux/socket.h:13:8: note: previous definition is here
struct __kernel_sockaddr_storage {
       ^
1 error generated.

Signed-off-by: spezi77 <spezi7713@gmx.net>